package com.cgi.cvportal.model;

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;

import com.fasterxml.jackson.annotation.JsonIgnore;

@Entity
@Table(name = "languages")
public class Language {

	// ------------------------
	// PRIVATE FIELDS
	// ------------------------

	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id; 

	@NotNull @NotEmpty
	private String code;
	
	@JsonIgnore
	@OneToMany(mappedBy="language",cascade=CascadeType.ALL, orphanRemoval=false)
	private Set<Cv> cvs;
	
	// ------------------------
	// PUBLIC METHODS
	// ------------------------

	public Language() {
	}

	public Language(Long id) {
		this.id = id;
	}

	public Language(String code) {
		this.code = code;
	}

	// Getter and setter methods
	public Long getId() {
		return id;
	}

	public void setId(Long value) {
		this.id = value;
	}
	
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}
	
	public Set<Cv> getCvs() {
		return cvs;
	}

	public void setCvs(Set<Cv> cvs) {
		this.cvs = cvs;
	}
} // class User