package com.cgi.cvportal.model;

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;

import com.fasterxml.jackson.annotation.JsonIgnore;

@Entity
@Table(name = "users")
public class User {

	// ------------------------
	// PRIVATE FIELDS
	// ------------------------

	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id; 

	// The user's email
	@NotNull @NotEmpty @Email
	private String email;

	// The user's name
	@NotNull @NotEmpty
	private String name;

	
	@JsonIgnore
	@OneToMany(mappedBy="user",cascade=CascadeType.ALL, orphanRemoval=true)
	private Set<Cv> cvs;
	
	// ------------------------
	// PUBLIC METHODS
	// ------------------------

	public User() {
	}

	public User(Long id) {
		this.id = id;
	}

	public User(String email, String name) {
		this.email = email;
		this.name = name;
	}

	// Getter and setter methods
	public Long getId() {
		return id;
	}

	public void setId(Long value) {
		this.id = value;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String value) {
		this.email = value;
	}

	public String getName() {
		return name;
	}

	public void setName(String value) {
		this.name = value;
	}
	
	public Set<Cv> getCvs() {
		return cvs;
	}

	public void setCvs(Set<Cv> cvs) {
		this.cvs = cvs;
	}
} // class User